### ISSUE TITLE
Windows Package Manager 1.3 change

### ISSUE THREAD

**Issue by denelon** [SamErde/Chocolately-Dip#2]
When Windows Package Manager 1.3 is released, the requirement for a logged in MSA may not be required for the package list.

**Comment by SamErde** [comment]
Thanks for the info, @denelon! Does this comment relate to any particular lines in my script?

**Comment by SamErde** [comment]
Thank you. That will be huge!

**Comment by SamErde** [comment]
Looks like this has been fixed with the latest stable [release](https://github.com/microsoft/winget-cli/releases/tag/v1.3.2091) and the [closure of issue 1585](https://github.com/microsoft/winget-cli/issues/1585)!
